### ISSUE TITLE
Publish new package version v0.0.8

### ISSUE THREAD

**Issue by Faisal-Manzer** [null-none/react-localstorage#4]
The last published version v0.0.7 was updated "a year ago"
We have some minor changes.

**Comment by null-none** [comment]
@Faisal-Manzer Thank you!

Hi null-none!

A new version of the package reactjs-localstorage (0.0.8) was published at 2019-10-05T09:56:30.648Z from
130.204.84.138. The shasum of this package was 34934d3ec81a2326e4604617edd193e60c4ec914.

If you have questions or security concerns, you can reply to this message or
email support@npmjs.com.

npm loves you.
