### ISSUE TITLE
No key is created in localStorage

### ISSUE THREAD

**Issue by worteepz** [null-none/react-localstorage#7]
Hello!

Thx for your module! He perfectly solved my server rendering problem!

![image](https://user-images.githubusercontent.com/21091849/82131283-3110b800-97dc-11ea-9771-121ba6a7096b.png)

When I save the data in the **localStorage** without module, they working perfect: when I reloaded the page or when I closed the page, the data from localStorage are not erased. 

After installing the module, the key of localStorage is not created in the browser:

https://yadi.sk/i/Bb36ZgJ-7zooeQ 

![image](https://user-images.githubusercontent.com/21091849/82131157-e6db0700-97da-11ea-96bd-3c202d854e9b.png)

This is what the array looks like when I use **localStorage** in Browser without your module.. (f12)

![image](https://user-images.githubusercontent.com/21091849/82131201-54873300-97db-11ea-9b51-2f9f22843837.png)

And this, when i use reactLocalStorage:

Storage in Browser is empty:

![image](https://user-images.githubusercontent.com/21091849/82131231-b2b41600-97db-11ea-86dd-220847233c85.png)

So, when i refresh or close page in browser, data and the key is empty.. 

Do you have any thoughts how to fix this?

Thanks!

**Comment by null-none** [comment]
@worteepz update the new version and check please.
